apiVersion: v2
name: ploigos-workflow-shared-cluster-resources
description: |
  A Helm chart for Kubernetes to deploy the cluster level resources required to
  deploy and run Ploigos Workflows no matter the workflow runner tool.
type: application
maintainers:
  - name: Red Hat, Inc.
    email: ploigos@redhat.com
# MANAGED BY: GitHub workflow
version: 0.19.0-edge.6
