apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: gitea-push
  labels:
    {{- include "ploigos-workflow-tekton-cluster-resources.labels" . | nindent 4 }}
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.html_url)
  - name: git-repo-ssh-url
    value: $(body.repository.ssh_url)
  - name: git-repo-event-target-ref
    value: $(body.extensions.branch_name)
  - name: pipelinerun-name
    value: $(body.extensions.pipelinerun_name)
