apiVersion: v2
name: ploigos-workflow-tekton-shared-resources
description: |
  A Helm chart for Kubernetes to install the shared resources for a Ploigos Workflow run
  by Tekton for a given application service.

  Not intended to be used on its own but rather as a sub chart for a specific Workflow.
type: application
maintainers:
  - name: Red Hat, Inc.
    email: tssc+ploigos@redhat.com
dependencies:
  - name: ploigos-workflow-shared-resources
    version: ">= 0.0.0 || >= 0.0.0-0"
# MANAGED BY: GitHub workflow
version: 0.15.0
