---
global:
  applicationName: test-app
  serviceName: test-srv

  stepRunnerConfigDir: cicd/step-runner-config

  workflowWorkerImageDefault: quay.io/tssc/tssc-base:latest
  workflowWorkerImagePackage: quay.io/tssc/tssc-tool-maven:nightly
  workflowWorkerImagePushArtifacts: quay.io/tssc/tssc-tool-maven:nightly

  # NOTE:
  #   have to test with ingress since GitHub action tests on 'kind' server where routes don't
  #   exist. Would much rather not have this hard coded in here and pass in at run time but....
  #   https://github.com/helm/chart-testing/issues/301
  eventListenerCreateRoute: false
  eventListenerCreateIngress: true
  eventListenerRouteHostOverride: el-test.ploigos.xyz
  eventListenerIngressHost: el-test.ploigos.xyz
