{{- if $.Values.global.eventListenerCreateRoute }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{include "ploigos-workflow-tekton.eventListenerIngressName" . }}
  labels:
    {{- include "ploigos-workflow.labels" . | nindent 4 }}
spec:
{{- if .Values.global.eventListenerRouteHostOverride }}
  host: {{ .Values.global.eventListenerRouteHostOverride }}
{{- end }}
  to:
    kind: Service
    name: {{ include "ploigos-workflow-tekton.eventListenerServiceName" .}}
    weight: 100
  port:
    targetPort: listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}