apiVersion: v2
name: ploigos-workflow-minimal-tekton-pipeline
description: |
  A Helm chart for Kubernetes to install the Ploigos Workflow (Minimal) run by Tekton for a
  given application service.
type: application
maintainers:
  - name: Red Hat, Inc.
    email: tssc+ploigos@redhat.com
dependencies:
  - name: ploigos-workflow-tekton-shared-resources
    version: ">= 0.0.0 || >= 0.0.0-0"
# MANAGED BY: GitHub workflow
version: 0.14.0-edge.2
